---
- name: Configure NTP on Cisco Switch
  hosts: CISCO-SW-01
  gather_facts: false

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_user: admin
    ansible_become: true
    ansible_become_method: ansible.netcommon.enable
    ansible_ssh_private_key_file: ""
    ansible_network_cli_ssh_type: paramiko

  tasks:
    - name: Configure NTP server
      cisco.ios.ios_config:
        lines:
          - ntp server pool.ntp.org

    - name: Save configuration
      cisco.ios.ios_config:
        save_when: always
# Updated Sun Mar 15 06:36:48 AM UTC 2026
