---
- name: syslog_config
  hosts: juniper-srx320
  gather_facts: false

  vars:
    ansible_connection: ansible.netcommon.netconf
    ansible_network_os: junipernetworks.junos.junos
    ansible_user: admin
    ansible_port: 830
    ansible_host: 192.168.99.1
    ansible_netconf_ssh_config: null
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_command_timeout: 120
    ansible_connect_timeout: 120

  tasks:
    - name: grafana_monitoring
      junipernetworks.junos.junos_config:
        lines:
          - set system syslog host 192.168.99.26 port 1514 any any
          - set system syslog host 192.168.99.26 port 1514 structured-data

    - name: commit configuration
      junipernetworks.junos.junos_config:
        confirm_commit: true
        comment: "SYSLOG configured via AWX"
