---
ansible_host: 192.168.0.5/24
ansible_port: 830
ansible_connection: ansible.netcommon.netconf
ansible_network_os: junipernetworks.junos.junos
ansible_command_timeout: 120
ansible_connect_timeout: 60
