name: Sync AWX Project

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sync AWX Project
        run: |
          curl -s -X POST "http://192.168.99.21:30080/api/v2/projects/10/update/" \
          -u admin:${{ secrets.AWX_PASSWORD }} \
          -H "Content-Type: application/json"
          echo "✅ Project synced! Run jobs manually from AWX GUI!"
