name: Deploy Network Config

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sync AWX Project
        run: curl -s -X POST "http://192.168.99.21:30080/api/v2/projects/10/update/" -u admin:${{ secrets.AWX_PASSWORD }} -H "Content-Type: application/json"

      - name: Run Cisco NTP
        run: curl -s -X POST "http://192.168.99.21:30080/api/v2/job_templates/12/launch/" -u admin:${{ secrets.AWX_PASSWORD }} -H "Content-Type: application/json"

      - name: Run Cisco SNMP
        run: curl -s -X POST "http://192.168.99.21:30080/api/v2/job_templates/13/launch/" -u admin:${{ secrets.AWX_PASSWORD }} -H "Content-Type: application/json"

      - name: Run SRX Job
        run: curl -s -X POST "http://192.168.99.21:30080/api/v2/job_templates/14/launch/" -u admin:${{ secrets.AWX_PASSWORD }} -H "Content-Type: application/json"

      - name: Done
        run: echo "All jobs triggered!"
